### PR TITLE
Adopt python f-strings using flynt

### PR DESCRIPTION
**Pull request by peterjc**
Means must drop support for Python 3.5

### CODE REVIEW

**Comment by peterjc** [comment]
There is something up with the dependencies on CircleCI right now, unrelated to this change.

**Comment by peterjc** [comment]
Interesting:

```
6.67s$ flake8 .
./thapbi_pict/assess.py:151:26: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/assess.py:242:18: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/assess.py:242:18: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/assess.py:364:17: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/assess.py:450:13: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/seq_import.py:59:9: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/dump.py:206:26: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/fasta_nr.py:89:22: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/prepare.py:250:26: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/sample_summary.py:53:13: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/utils.py:688:18: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/classify.py:286:9: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/classify.py:370:21: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/classify.py:396:26: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/classify.py:399:9: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/classify.py:403:13: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/classify.py:530:22: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/classify.py:638:26: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/classify.py:670:26: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/conflicts.py:79:26: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/edit_graph.py:374:9: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/edit_graph.py:374:9: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/edit_graph.py:530:13: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
./thapbi_pict/db_import.py:244:25: PIE782: Unnecessary f-string. You can safely remove the `f` prefix.
```

Looks like some flake8 false positives, e.g.

```python
handle.write(f"#{level}-count\tExpected\tPredicted\n")
```

The f-string works just fine:

```
>>> level = 123
>>> f"#{level}-count\tExpected\tPredicted\n"
'#123-count\tExpected\tPredicted\n'
```

**Comment by peterjc** [comment]
Cross reference https://github.com/sbdchd/flake8-pie/issues/24

**Comment by peterjc** [comment]
Any thoughts on f-strings @widdowquinn ?

**Comment by widdowquinn** [comment]
I like them, I use them, and they restrict you to Python >3.6 (which isn't the worst thing in the world, and post-Python2 is easier to justify).

**Comment by peterjc** [comment]
Good - I'll apply this then.

For logging, look into setting ``style="{"`` over the default ``style="%"``
https://docs.python.org/3/library/logging.html

**Pull request merged**
