### PR TITLE
Restructure how we store the curated ITS1 sequences

### PR DESCRIPTION
**Pull request by peterjc**
It has become clear that the curated ITS1 set is not as static as I assumed when we started the project - and the *legacy* naming is also inappropriate.

The idea here to to drop the ``database/legacy/*.fasta`` folder of snapshots, replacing them with ``database/Phytophthora_ITS1_curated.fasta`` instead (single file under version control).

Also, I am re-writing the file contents to mimic a (reduced) NCBI layout,

```
>accession genus species strain etc
sequence
```

With multiple entries following the NCBI BLAST NR FASTA file style, using ctrl+a (i.e. ASCII 0x01):

```
>accession1 genus species(ctrl+a)accession2 genus species
sequence
```

These are now sorted by the sequence, which makes the file's version history easier to track (previous revisions sometimes changed the order).

With this done, we can replace the``thapbi-pict legacy-import`` command, and just use ``thapbi-pict ncbi-import`` here.

We can then delete ``thapbi_pict/legacy.py`` with all its *ad hoc* parsing code.

### CODE REVIEW

**Comment by peterjc** [comment]
I'm also considering replacing the ``legacy-import`` with a ``curated-import`` where the FASTA entries are just accession species (no free text like the NCBI FASTA file), which would also default to no left/right primer trimming.

**Comment by peterjc** [comment]
What are your thoughts on this @widdowquinn ?

**Comment by widdowquinn** [comment]
That all seems very considered and sensible. I'm in favour.

**Comment by peterjc** [comment]
Oh good, because reverting would be a pain 👍

**Comment by widdowquinn** [comment]
Just in case you're wondering, that's not the only reason I'm in favour ;)

**Pull request merged**
